config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :orders
  resources :plates
  resources :users

  scope module: :api, path: "api" do
    resources :clients
    resources :plates
    resources :orders
    resources :users
  end

  root "sessions#new"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :users, except: [:new]
  get "menu", to: "menu#show"


end

app/models/plate.rb
class Plate < ApplicationRecord

    has_many :orders
    has_one_attached :picture
    has_rich_text :description
end

app/controllers/api/plates_controller.rb
module Api 
    class PlatesController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :set_plate, only: %i[ show edit update destroy ]
  
      def index
        @plates = Plate.all
      end
  
      def show
      end
  
      def new
        @plate = Plate.new
      end
  
      def edit
      end
  
      def create
        @plate = Plate.new(plate_params)
  
  
          if @plate.save
            render 'api/plates/show', status: :created
          else
            render json: @plate.errors, status: :unprocessable_entity
          end
        
      end
  
      def update
        if @plate.update(plate_params)
          render 'api/plates/show', status: :ok, location: @plate
        else
          render json: @plate.errors, status: :unprocessable_entity
        end
      end
  
      def destroy
        @plate.destroy
  
          render 'api/plates/index', status: :ok
      end
    
  
      private
        def set_plate
          @plate = Plate.find(params[:id])
        end
  
        def plate_params
            params.require(:plate).permit(:name, :description, :price, :picture, :order_id)
        end
    end
  end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: %i[ show edit update destroy ]

  def index
    if require_user or authenticated_user
    else
    @plates = Plate.all
    end
  end

  def show
    if require_user or authenticated_user
    end
  end

  def new
    if require_user or authenticated_user
    else
    @plate = Plate.new
    end
  end

  def edit
    if require_user or authenticated_user
    end
  end

  def create
    if require_user or authenticated_user
    else
    @plate = Plate.new(plate_params)

    respond_to do |format|
      if @plate.save
        format.html { redirect_to plate_url(@plate), notice: "Plate was successfully created." }
        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  def update
    if require_user or authenticated_user
    else
    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to plate_url(@plate), notice: "Plate was successfully updated." }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  def destroy
    if require_user or authenticated_user
    else
    @plate.destroy

    respond_to do |format|
      format.html { redirect_to plates_url, notice: "Plate was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  end

  private
    def set_plate
      @plate = Plate.find(params[:id])
    end

    def plate_params
      params.require(:plate).permit(:name, :description, :price, :picture, :order_id)
    end
    
    
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/views/plates/_form.html.haml
= form_with(model: plate) do |form|
  - if plate.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(plate.errors.count, "error")
        prohibited this plate from being saved:
      %ul
        - plate.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :description, style: "display: block"
    = form.rich_text_area :description
  %div
    = form.label :price, style: "display: block"
    = form.number_field :price
  %div
    = form.label :picture, style: "display: block"
    = form.file_field :picture
  %div
    = form.submit

app/views/plates/_plate.html.haml
%div{:id => "#{dom_id plate}"}
  %p
    %strong Name:
    = plate.name
  %p
    %strong Description:
    = plate.description
  %p
    %strong Price:
    = plate.price
  %img
    %strong Picture:
    = image_tag(plate.picture, style: 'height:35%;width:35%')

app/views/plates/edit.html.haml
%h1 Editing plate
= render "form", plate: @plate
%br/
%div
  = link_to "Show this plate", @plate
  |
  \#{link_to "Back to plates", plates_path}

app/views/plates/index.html.haml
.page-header.m-4
  %p{:style => "color: green"}= notice

  %h1.mb-4
    = "List of plates"
    .float-right
      = link_to "New plate",
                new_plate_path, class: "btn btn-primary"



%table.table.table-striped
  %thead
    %tr
      %th= "Name"
      %th= "Description"
      %th= "Price"
      %th= "Picture"

  %tbody
    - @plates.each do |plate|
      %tr
        %td= plate.name
        %td= plate.description
        %td= plate.price
        %td= image_tag(plate.picture, style: 'height:45%;width:25%')
        %td= link_to "Show this plate", plate, class: "btn btn-info"
        %td= link_to "Edit this plate", edit_plate_path(plate), class: "btn btn-success"
        %td= button_to "Delete this plate", plate, method: :delete, class: "btn btn-danger"

app/views/plates/new.html.haml
%h1 New plate
= render "form", plate: @plate
%br/
%div
  = link_to "Back to plates", plates_path

app/views/plates/show.html.haml
%p{:style => "color: green"}= notice
= render @plate
%div
  = link_to "Edit this plate", edit_plate_path(@plate)
  |
  \#{link_to "Back to plates", plates_path}
  
  \#{button_to "Destroy this plate", @plate, method: :delete}