config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :orders
  resources :plates
  resources :users

  scope module: :api, path: "api" do
    resources :clients
    resources :plates
    resources :orders
    resources :users
  end

  root "sessions#new"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :users, except: [:new]
  get "menu", to: "menu#show"


end

app/models/client.rb
class Client < ApplicationRecord

    has_many :orders
end

app/controllers/api/clients_controller.rb
 module Api 
  class ClientsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_client, only: %i[ show edit update destroy ]

    def index
      @clients = Client.all
    end

    def show
    end

    def new
      @client = Client.new
    end

    def edit
    end

    def create
      @client = Client.new(client_params)


        if @client.save
          render 'api/clients/show', status: :created
        else
          render json: @client.errors, status: :unprocessable_entity
        end
      
    end

    def update

        if @client.update(client_params)
          render 'api/clients/show', status: :created
        else
          render json: @client.errors, status: :unprocessable_entity
        end
      
    end

    def destroy
      @client.destroy

        render 'api/clients/index', status: :ok
    end
  

    private
      def set_client
        @client = Client.find(params[:id])
      end

      def client_params
        params.require(:client).permit(:name, :email, :password, :direction)
      end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :email, :password, :direction)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.haml
%div{:id => "#{dom_id client}"}
  %p
    %strong Name:
    = client.name
  %p
    %strong Email:
    = client.email
  %p
    %strong Password:
    = client.password
  %p
    %strong Direction:
    = client.direction

app/views/clients/_form.html.haml
= form_with(model: client) do |form|
  - if client.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :email, style: "display: block"
    = form.text_field :email
  %div
    = form.label :password, style: "display: block"
    = form.password_field :password
  %div
    = form.label :direction, style: "display: block"
    = form.text_field :direction
  
  .from-group
    = form.submit

app/views/clients/edit.html.haml
%h1 Editing client
= render "form", client: @client
%br/
%div
  = link_to "Show this client", @client
  |
  \#{link_to "Back to clients", clients_path}

app/views/clients/index.html.haml
.page-header.m-4
  %p{:style => "color: green"}= notice

  %h1.mb-4
    = "List of clients"
    .float-right
      = link_to "New client",
                new_client_path, class: "btn btn-primary"

%table.table.table-striped
  %thead
    %tr
      %th= "Name"
      %th= "Email"
      %th= "Password"
      %th= "Direction"

  %tbody
    - @clients.each do |client|
      %tr
        %td= client.name
        %td= client.email
        %td= client.password
        %td= client.direction
        %td= link_to "Show this client", client, class: "btn btn-info"
        %td= link_to "Edit this client", edit_client_path(client), class: "btn btn-success"
        %td= button_to "Delete this client", client, method: :delete, class: "btn btn-danger"

app/views/clients/new.html.haml
%h1 New client
= render "form", client: @client
%br/
%div
  = link_to "Back to clients", clients_path

app/views/clients/show.html.haml
.page-header.m-4
  %p{:style => "color: green"}= notice

.card.ml-4.m-4
  .card-body
    %strong= "Name:"
    %p.card-text &nbsp #{@client.name}
.card.ml-4.m-4
  .card-body
    %strong= "Email"
    %p.card-text &nbsp #{@client.email}
.card.ml-4.m-4
  .card-body
    %strong= "Password "
    %p.card-text &nbsp #{@client.password}
.card.ml-4.m-4
  .card-body
    %strong= "Direction "
    %p.card-text &nbsp #{@client.direction}

.row.mt-3
  .offset-3.col-3
    = link_to "Back to clients",
                clients_path, class: "btn btn-secondary btn-block"
    = link_to "Edit this client", edit_client_path(@client), class: "btn btn-secondary btn-block"