config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :orders
  resources :plates
  resources :users

  scope module: :api, path: "api" do
    resources :clients
    resources :plates
    resources :orders
    resources :users
  end

  root "sessions#new"
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :users, except: [:new]
  get "menu", to: "menu#show"


end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ProyectoLenguajes
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    %meta{:content => "width=device-width, initial-scale= 1", :name => "viewport"}/
  %body
    %header.container
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            = link_to "Menu", menu_path, class: "navbar-brand"
          %ul.nav.navbar-nav.navbar-right
            - if logged_in?
              %li= link_to "Users", users_path
              %li= link_to "Recipes", plates_path
              %li= link_to "Clients", clients_path
              %li= link_to "Orders", orders_path
              %li= link_to "Log out", logout_path, method: :delete
            - else
              %li= link_to "Log In", login_path
    %section.container
      #flash
        - flash.each do |key, value|
          %div{:class => "flash alert #{alert_class(key)}"}= value
      = yield